source 'https://github.com/CocoaPods/Specs.git'  # 官方库

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def swift_pods
    pod 'Alamofire'
#    pod 'AlamofireSwiftyJSON'

    pod 'AlamofireSwiftyJSON', :git =>'https://github.com/Xinguang/AlamofireSwiftyJSON.git'

    pod 'SnapKit'
    pod 'RxSwift'
    pod 'RxCocoa'
#    pod 'ObjectMapper'
    pod 'AlamofireObjectMapper', '~> 4.0'
    pod 'NSObject+Rx'
    pod 'R.swift', '~> 3.1.0'
#    pod 'TransitionTreasury', '~> 3.0.4'
    pod 'Moya'
    pod 'Moya/RxSwift'
    pod 'Moya-ObjectMapper/RxSwift'
#    五角星
#    https://github.com/evgenyneu/Cosmos
#    pod 'Cosmos', '~> 10.0'
#    https://github.com/WenchaoD/FSPagerView
#    pod 'FSPagerView'
#    pod 'SwiftyJSON'
#    pod 'KMPlaceholderTextView'
#    pod 'TTTAttributedLabel'
    
#    pod 'DKImagePickerController' # add by zzl
    
    # pay and share
#    pod 'MonkeyKing'
    # chat
#    pod 'ChatKit', '0.8.5'
end

def oc_pods
#    pod 'MMPopupView'
    pod 'MBProgressHUD'
#    pod 'CTVideoPlayerView'
    pod 'BMPlayer'


    pod "AVOSCloud" , "~> 6.1.0"
    pod "AVOSCloudIM", "~> 6.1.0"
    pod "MJRefresh" , "~> 3.1.9"
    pod "Masonry" , "~> 1.0.1"
    pod "SDWebImage" , "~> 3.8.0"
    pod "FMDB" , "~> 2.6.2"
    pod "pop", "~> 1.0.9"
    pod "UITableView+FDTemplateLayoutCell" , "~> 1.5.beta"
    pod "FDStackView" , "~> 1.0"
    pod "DACircularProgress" , "~> 2.3.1"
    pod "MLLabel" , "~> 1.9.2"
    pod "MWPhotoBrowser", "~> 2.1.2"
    pod "CYLDeallocBlockExecutor", "~> 1.1.2"
    
#   Ex
    pod 'CYLTabBarController', '1.9.0'
    pod 'TWMessageBarManager', '1.8.1'
    pod 'MLPAutoCompleteTextField', '1.5'
    pod 'FTPopOverMenu', '1.3.2'
    pod 'RedpacketLib' ,'3.4.1'
    pod 'FXForms', '1.2.14'
    pod 'AliyunOSSiOS', '~> 2.6.0'
end

target 'MalayRechargeSelfCheck' do
    swift_pods
#    oc_pods
end

#target 'Lawer' do
#    swift_pods
#    oc_pods
#end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

